# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akirachix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('description', models.TextField(default='Python Guru')),
                ('availability_date', models.DateField(default=datetime.date(2017, 1, 1))),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='graduation_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AddField(
            model_name='students',
            name='registration_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
    ]
